### PR TITLE
[grpc-web]support to generate sub for gRPC-web

### PR DESCRIPTION
**Pull request by seanliu1**
**Background**
Given gRPC does not use URLSession which providers us many handy tool to handle network call, we will have our own script to generate our struct which will contains path, input protobuf and output protobuf, etc. 

The usage will be protoc test.proto --swift_out=. --swiftgrpc_out=Client=false,Server=false:.
It will generate test.qrpc.swift file

On the client side, we have BaseClientStub, which will construct request body and parse the response based on grpc-web 

**Change**
Add new options for qrpc, add new Generator-Web file

**Test**
Make sure generated code can compile

### CODE REVIEW

**Comment by ericbuehl** [comment]
i'll hold off reviewing this until we have concluded this is the direction we want to go

**Comment by ericbuehl** [comment]
lets scrub the "QuibiRPC" references here as the protocol we are now supporting is grpc-web

**Comment by seanliu1** [comment]
sure, I will change everything to Web. Instead of Client, Sever, the option we add will be Web instead of Quibi.  Sound good? @ericbuehl

**Comment by Bankq** [comment]
Second "Quibi->Web", we should target https://github.com/grpc/grpc-swift/issues/174

**Comment by ericbuehl** [comment]
we should also detect if any services specify a stream type and blow up if they do (or add support for them :) )

**Comment by seanliu1** [comment]
> there's a ton of autogenerated code in here. some of it looks like formatting. can you trim it down to only the necessary changes?

It looks like many changes are real change, not sure they are byproduct of "make all". I will try to exclude them (SwiftGRPC-Carthage.xcodeproj/project.pbxproj, xcscheme etc)

**Pull request closed without merging**
